// scripts/migration/import.cjs
// Generates a single SQL script to import all transformed data into SQLite/D1.
// Orders tables to respect foreign key constraints.

const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, 'data');
const sqlFile = path.join(dataDir, 'import_seed.sql');

// Ordered tables to satisfy foreign key constraints
const TABLE_ORDER = [
  'packages',
  'templates',
  'profiles',
  'invitations',
  'events',
  'guests',
  'rsvps',
  'wishes',
  'gifts',
  'media',
  'checkins',
  'promos',
  'transactions',
  'music_library',
  'system_settings'
];

// SQLite string escape helper
function escapeSqlValue(value) {
  if (value === null || value === undefined) {
    return 'NULL';
  }
  if (typeof value === 'number') {
    return value.toString();
  }
  if (typeof value === 'string') {
    return `'${value.replace(/'/g, "''")}'`;
  }
  // fallback
  return `'${value.toString().replace(/'/g, "''")}'`;
}

function generateInsertStatement(table, row) {
  const columns = Object.keys(row);
  const values = Object.values(row).map(escapeSqlValue);

  return `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${values.join(', ')}) ON CONFLICT DO NOTHING;`;
}

function runImportGenerator() {
  console.log("=== MEMULAI GENERASI SQL SCRIPT IMPORT ===");
  
  let sqlContent = [];
  sqlContent.push("-- SQL Import Seed Script generated by import.cjs");
  sqlContent.push("-- Disables foreign key checks during import for safety");
  sqlContent.push("PRAGMA defer_foreign_keys = ON;");
  sqlContent.push("");

  let totalRows = 0;

  for (const table of TABLE_ORDER) {
    const transformedPath = path.join(dataDir, `${table}_transformed.json`);
    if (!fs.existsSync(transformedPath)) {
      console.log(`Informasi: Berkas ${table}_transformed.json tidak ditemukan, dilewati...`);
      continue;
    }

    try {
      const data = JSON.parse(fs.readFileSync(transformedPath, 'utf-8'));
      if (data.length === 0) continue;

      sqlContent.push(`-- Table: ${table} (Total rows: ${data.length})`);
      for (const row of data) {
        sqlContent.push(generateInsertStatement(table, row));
        totalRows++;
      }
      sqlContent.push("");
      
      console.log(`Menambahkan ${data.length} perintah INSERT untuk tabel "${table}"`);
    } catch (error) {
      console.error(`Gagal memproses tabel ${table}:`, error.message || error);
    }
  }

  sqlContent.push("PRAGMA defer_foreign_keys = OFF;");

  try {
    fs.writeFileSync(sqlFile, sqlContent.join('\n'), 'utf-8');
    console.log(`\n=== SQL SCRIPT IMPORT BERHASIL DIBUAT ===`);
    console.log(`Lokasi berkas SQL: ${sqlFile}`);
    console.log(`Total perintah INSERT: ${totalRows}`);
  } catch (error) {
    console.error("Gagal menulis file SQL:", error.message || error);
  }
}

runImportGenerator();
